routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

function getUrlParent($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null){
        return $pm->slug.'/';
    }
    else {
       return   getUrlParent($pm->parent_id). $pm->slug.'/';
    }

}


function getUrlController($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null) {
        return $pm->controller_name.'\\';
    }
    else {
        return   getUrlController($pm->parent_id). $pm->controller_name.'\\';
    }

}

function getUrlName($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null) {
        return $pm->slug.'.';
    }
    else {
        return   getUrlName($pm->parent_id). $pm->slug.'.';
    }

}

Route::get('/', function () {
    return redirect('/cms');
})->name('welcome');

Auth::routes();
Route::get('cms/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('cms/login', 'Auth\LoginController@login')->name('login');

Route::post('/contact-us/mail','HomeController@mailContact')->name('contact.post');
Route::get('/ajax-select', 'HomeController@ajaxSelect')->name('ajax-select');

Route::group([ 'middleware' => ['roles'], 'prefix'=>'cms'], function () {
    $modules = \App\Models\Module::all();
    foreach ( $modules as $module ){

        Route::resource( getUrlParent($module->parent_id).$module->slug, getUrlController($module->parent_id).$module->controller_name,
            ['as' => substr(getUrlName($module->parent_id), 0, -1)]);
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{id}/remove-image',
            getUrlController($module->parent_id).$module->controller_name.'@removeImage')
            ->name(getUrlName($module->parent_id).$module->slug.'.removeImage');

        Route::get(getUrlParent($module->parent_id).$module->slug.'/{id}/edit/authorize',
            getUrlController($module->parent_id).$module->controller_name.'@editAuthorise')
            ->name(getUrlName($module->parent_id).$module->slug.'.edit-authorise');
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{user}/up', getUrlController($module->parent_id).$module->controller_name.'@up')
            ->name(getUrlName($module->parent_id).$module->slug.'.up');
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{user}/down', getUrlController($module->parent_id).$module->controller_name.'@down')
            ->name(getUrlName($module->parent_id).$module->slug.'.down');
    }
    Route::get('/', 'HomeController@index')->name('home');
    $pmodules = \App\Models\ParentModule::query()->whereNull('parent_id')->get();
    foreach ($pmodules as $mod){

//        \Illuminate\Support\Facades\Log::info($mod->hasConfig());
        Route::get($mod->slug, $mod->controller_name.'\\'.$mod->controller_name.'Controller@show')->name($mod->slug);
        if ( $mod->hasConfig()->count() > 0){
            Route::get($mod->slug.'/configuration', $mod->controller_name.'\\'.$mod->controller_name.'Controller@configuration')
                ->name($mod->slug.'.configuration');
            Route::post($mod->slug.'/configuration', $mod->controller_name.'\\'.$mod->controller_name.'Controller@configuration')
                ->name($mod->slug.'.configuration.store');
        }
    }

    Route::group([ 'prefix'=>'configuration','middleware' => ['roles'] ], function () {
        Route::get('remove/{key}','Configuration\ConfigurationController@removeImage')->name('configuration.remove');
        Route::get('branding','Configuration\ConfigurationController@indexBranding')->name('configuration.branding');
        Route::post('branding','Configuration\ConfigurationController@brandingStore')->name('configuration.branding.store');
        Route::get('domain','Configuration\ConfigurationController@indexDomain')->name('configuration.domain');
        Route::post('domain','Configuration\ConfigurationController@domainStore')->name('configuration.domain.store');
        Route::get('super-user','Configuration\ConfigurationController@indexSuperUser')->name('configuration.super-user');
        Route::post('super-user','Configuration\ConfigurationController@superUserStore')->name('configuration.super-user.store');
        
        Route::resource('api-argument', 'Configuration\ApiArgumentController');
        Route::get('api-argument/{api-argument}/up', 'Configuration\ApiArgumentController@up')->name('api-argument.up');
        Route::get('api-argument/{api-argument}/down', 'Configuration\ApiArgumentController@down')->name('api-argument.down');Route::get('api-argument/{id}/edit/authorize','Configuration\ApiArgumentController@editAuthorise')->name('api-argument.edit-authorise');


        Route::resource('contact-phone', 'OrganizationsManagement\ContactSystem\ContactPhoneController');
        Route::get('contact-phone/{contact-phone}/up', 'OrganizationsManagement\ContactSystem\ContactPhoneController@up')->name('contact-phone.up');
        Route::get('contact-phone/{contact-phone}/down', 'OrganizationsManagement\ContactSystem\ContactPhoneController@down')->name('contact-phone.down');Route::get('lead-action/{id}/edit/authorize','ProjectManagement\ProjectSystem\LeadActionController@editAuthorise')->name('lead-action.edit-authorise');



        Route::resource('api-generator','Configuration\ApiController');
        Route::get('api-generator/{api}/up', 'Configuration\ApiController@up')->name('api-generator.up');
        Route::get('api-generator/{api}/down', 'Configuration\ApiController@down')->name('api-generator.down');
        Route::get('api-generator/{id}/edit/authorize','Configuration\ApiController@editAuthorise')->name('api-generator.edit-authorise');

        Route::resource('domain', 'Configuration\DomainController');
        Route::get('domain/{domain}/up', 'Configuration\DomainController@up')->name('domain.up');
        Route::get('domain/{domain}/down', 'Configuration\DomainController@down')->name('domain.down');
        Route::get('domain/{id}/edit/authorize','Configuration\DomainController@editAuthorise')->name('domain.edit-authorise');

        Route::resource('status', 'Configuration\StatusController');
        Route::get('status/{status}/up', 'Configuration\StatusController@up')->name('status.up');
        Route::get('status/{status}/down', 'Configuration\StatusController@down')->name('status.down');
        Route::get('status/{id}/edit/authorize','Configuration\StatusController@editAuthorise')->name('status.edit-authorise');



        Route::get('language','Configuration\ConfigurationController@indexLanguage')->name('configuration.language');
        Route::get('language/change/{language}','Configuration\ConfigurationController@languageChange')->name('configuration.language.change');
        Route::get('language/create','Configuration\ConfigurationController@createLang')->name('configuration.language.create');
        Route::post('language/store','Configuration\ConfigurationController@storeLanguage')->name('configuration.language.store');


    });
    Route::group(['middleware' => ['roles'] ], function () {

        Route::resource('project-management/dashboard', 'ProjectManagement\ProjectSystem\DashboardController');
        Route::get('project-management/dashboard', 'ProjectManagement\ProjectSystem\DashboardController@index')->name('project-management/dashboard.index');

        Route::get('user','ProfileController@edit')->name('profile');
        Route::get('user/remove-image','ProfileController@removeImage')->name('profile.removeImage');
        Route::post('user/update','ProfileController@update')->name('profile.update');

        Route::resource('lead-action', 'ProjectManagement\LeadSystem\LeadActionController');
        Route::get('lead-action/{lead-action}/up', 'ProjectManagement\LeadSystem\LeadActionController@up')->name('lead-action.up');
        Route::get('lead-action/{lead-action}/down', 'ProjectManagement\LeadSystem\LeadActionController@down')->name('lead-action.down');
        Route::get('lead-action/{id}/edit/authorize','ProjectManagement\LeadSystem\LeadActionController@editAuthorise')->name('lead-action.edit-authorise');

        Route::resource('project-module', 'ProjectManagement\ProjectSystem\ProjectModuleController');
        Route::get('project-module/{project-module}/up', 'ProjectManagement\ProjectSystem\ProjectModuleController@up')->name('project-module.up');
        Route::get('project-module/{project-module}/down', 'ProjectManagement\ProjectSystem\ProjectModuleController@down')->name('project-module.down');
        Route::get('project-module/{id}/edit/authorize','ProjectManagement\ProjectSystem\ProjectModuleController@editAuthorise')->name('project-module.edit-authorise');

        Route::resource('project-task', 'ProjectManagement\ProjectSystem\ProjectTaskController');
        Route::get('project-task/{project-task}/up', 'ProjectManagement\ProjectSystem\ProjectTaskController@up')->name('project-task.up');
        Route::get('project-task/{project-task}/down', 'ProjectManagement\ProjectSystem\ProjectTaskController@down')->name('project-task.down');
        Route::get('project-task/{id}/edit/authorize','ProjectManagement\ProjectSystem\ProjectTaskController@editAuthorise')->name('project-task.edit-authorise');

    });

});

resources/views/project-management/lead-system/lead-action/lead-action-update.blade.php
@extends('layouts.app')

@section('content')
        <form id="main-form">
                <input type="hidden" name="_method" value="put">
                @csrf
                <div id="1" class="tab-content tab-content-profile" style="display:block;">
                    <div class="row">
                        <div class="container">
                            <div class="col-md-11">
                                {{--<div class="form-group">--}}
                                    {{--<label for="user_id" class="control-label">Assigned To </label>--}}
                                    {{--<select type="text" class="form-control select2" id="user_id" name="user_id">--}}
                                        {{--@foreach($users as $user)--}}
                                            {{--<option value="{{$user->id}} "@if($user->id == $leadAction->user_id) selected @endif >{{$user->name}}</option>--}}
                                        {{--@endforeach--}}
                                    {{--</select>--}}
                                    {{--<label id="user_id-error" class="control-label error"></label>--}}
                                {{--</div>--}}

                                <div class="form-group">
                                    <label for="contact_id" class="control-label">Contact</label>
                                    <select type="text" class="form-control select2" id="contact_id" name="contact_id">
                                        @foreach($contacts as $contact)
                                            <option value="{{$contact->id}}" @if($contact->id == $leadAction->contact_id) selected @endif  >{{$contact->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="contact_id-error" class="control-label error"></label>
                                </div>


                                <div class="form-group">
                                    <label for="created_date" class="control-label">Created Date</label>
                                    <div class="date-box">
                                        <div class="date-icon-box" >
                                            <span class="fa fa-calendar" id="created_date_icon"></span>
                                        </div>
                                        <input type="date" class="form-control" id="created_date" name="created_date"  data-date-format="DD-MM-YYYY" value="{{$leadAction->created_date}}">
                                    </div>
                                    <label id="created_date-error" class="control-label error"></label>
                                </div>

                                <div class="form-group">
                                    <label for="status_id" class="control-label">Status</label>
                                    <select type="text" class="form-control select2" id="status_id" name="status_id">
                                        @foreach($statuses as $status)
                                            <option value="{{$status->id}}" @if($status->id == $leadAction->status_id) selected @endif>{{$status->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="status_id-error" class="control-label error"></label>
                                </div>
                                {{--<div class="form-group">--}}
                                    {{--<label for="lead_id" class="control-label">Belongs to</label>--}}
                                    {{--<select type="text" class="form-control select2" id="lead_id" name="lead_id">--}}
                                        {{--@foreach($leads as $lead)--}}
                                            {{--<option value="{{$lead->id}}" @if($lead->id == $leadAction->lead_id) selected @endif >{{$lead->name}}</option>--}}
                                        {{--@endforeach--}}
                                    {{--</select>--}}
                                    {{--<label id="lead_id-error" class="control-label error"></label>--}}
                                {{--</div>--}}

                                <div class="form-group">
                                    <label for="type_id" class="control-label">Type</label>
                                    <select type="text" class="form-control select2" id="type_id" name="type_id">
                                        <option value="">Select Contact Type</option>
                                        @foreach($contactTypes as $contactType)
                                            <option value="{{$contactType->id}}" @if($contactType->id == $leadAction->type_id) selected @endif>{{$contactType->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="type_id-error" class="control-label error"></label>
                                </div>




                                <div class="form-group">
                                    <label for="note" class="control-label">Note</label>
                                    <textarea class="form-control" id="note" name="note" >{!! $leadAction->note !!} </textarea>
                                    <label id="note-error" class="control-label error"></label>
                                </div>

                                <div class="form-group">
                                    <label for="attachment" class="control-label">Attachment</label>
                                    <div class="box image-box" >
                                        <a href="" class="popup_selector" data-inputid="attachment">Browse Attachment</a>
                                        <input type="text" id="attachment" name="attachment" ">
                                    </div>
                                   {{--@if(isset($leadAction->attachment) and ($leadAction->attachment != null))--}}
                                        {{--<a type="text" href="{{asset($leadAction->attachment)}}" target="_blank" >{{asset($leadAction->attachment)}}</a>--}}
                                   {{--@endif--}}
                                    <label id="attachment-error" class="control-label error"></label>
                                {{--</div>--}}

                                {{--<div class="form-group">--}}
                                    <label for="att" class="control-label"></label>
                                    @if(isset($leadAction->attachment) and ($leadAction->attachment != null))
                                        <input type="hidden" id="video" name="video" value="{{asset($leadAction->attachment)}}" >
                                        <a type="text" class="form-control" id="att" name="att" href="{{asset($leadAction->attachment)}}">{{asset($leadAction->attachment)}}</a>
                                    @endif
                                    <label id="att-error" class="control-label error"></label>
                                </div>



                            </div>

                        </div>
                    </div>
                </div>
            @include('layouts.partials.form-action-buttons',['submit'=>true,'back'=>true])
        </form>
@endsection

@push('css')
    <link href="{{asset('css/colorbox.css')}}" rel="stylesheet">
@endpush
@push('js')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
    <script src="{{asset('packages/ckeditor/ckeditor.js')}}"></script>
    <script>
        CKEDITOR.replace( 'note' );
    </script>
    <script type="text/javascript" src="{{asset('js/jquery.colorbox-min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/standalonepopup.min.js')}}"></script>

    <script>
        $(function(){

            $("input").on("change", function() {
                this.setAttribute(
                    "data-date",
                    moment(this.value, "YYYY-MM-DD")
                        .format( this.getAttribute("data-date-format") )
                )
            }).trigger("change");



        });
    </script>

    <script>
        $(function () {
            $('.select2').select2({
                width: '100%'
            });
        })
        $('#form-back').click(function () {
            location.href='{{route('project-management.lead-system.lead.index')}}' + '/' + '{{$leadAction->lead_id}}' +'/edit'
        });
        $('#form-reset').on('click',function () {
            $('#main-form')[0].reset();
        })
        $('#form-submit').click(function () {
            var counter = 0;
            @foreach($fields['update'] as $k=>$field)

            if( $('#{{$field}}').val() =='' ){
                $('#{{$field}}-error').text('This field is required');
                counter++;
            }
            @endforeach
            if ( counter > 0 ){
                return;
            }
            // tinyMCE.triggerSave();

            var content = CKEDITOR.instances.note.getData();
            var data = new FormData();
            //Form data
            var form_data = $('#main-form').serializeArray();
            $.each(form_data, function (key, input) {
                data.append(input.name, input.value);
            });
            data.append('_token', '{{csrf_token()}}');
            data.append('note', content);
            $.ajax({
                type: "POST",
                processData: false,
                contentType: false,
                url: '{{route('lead-action.update', $leadAction->id)}}',
                data: data,
                success: function(data)
                {
                    console.log(data);
                    if(data != null){
                        location.href='{{route('project-management.lead-system.lead.index')}}/{{$leadAction->lead_id}}/edit#leadAction';
                    }
                },
                error:function( data){
                    console.log(data);
                }
            });

        });
    </script>
@endpush

resources/views/project-management/lead-system/lead-action/lead-action.blade.php
@extends('layouts.app')

@section('content')

            <form id="main-form">
                @if(app('request')->has('lead_id'))
                    <input type="text" name="lead_id" value="{{app('request')->get('lead_id')}}" hidden>
                @endif
                @csrf
                <div id="1" class="tab-content tab-content-profile" style="display:block;">
                    <div class="row">
                        <div class="container">
                            <div class="col-md-11">

                                {{--<div class="form-group">--}}
                                    {{--<label for="user_id" class="control-label">Assigned To </label>--}}
                                    {{--<select type="text" class="form-control select2" id="user_id" name="user_id">--}}
                                        {{--<option value="">Select User</option>--}}
                                        {{--@foreach($users as $user)--}}
                                            {{--<option value="{{$user->id}}" @if (auth()->user()->id == $user->id) selected @endif  >{{$user->name}}</option>--}}
                                        {{--@endforeach--}}
                                    {{--</select>--}}
                                    {{--<label id="user_id-error" class="control-label error"></label>--}}
                                {{--</div>--}}

                                <div class="form-group">
                                    <label for="contact_id" class="control-label">Contact</label>
                                    <select type="text" class="form-control select2" id="contact_id" name="contact_id">
                                        <option value="">Select Contact</option>
                                        @foreach($contacts as $contact)
                                            <option value="{{$contact->id}}" @if($lead->contact_id == $contact->id)selected @endif >{{$contact->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="contact_id-error" class="control-label error"></label>
                                </div>

                                <div class="form-group">
                                    <label for="created_date" class="control-label">Created Date</label>
                                    <div class="date-box">
                                        <div class="date-icon-box" >
                                            <span class="fa fa-calendar" id="created_date_icon"></span>
                                        </div>
                                        <input type="date" class="form-control" id="created_date" name="created_date"  data-date-format="DD-MM-YYYY">
                                    </div>
                                    <label id="created_date-error" class="control-label error"></label>
                                </div>
                                <div class="form-group">
                                    <label for="type_id" class="control-label">Type<span class="star-required">*</span></label>
                                    <select type="text" class="form-control select2" id="type_id" name="type_id">
                                        <option value="">Select Type</option>
                                        @foreach($contactTypes as $contactType)
                                            <option value="{{$contactType->id}}">{{$contactType->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="type_id-error" class="control-label error"></label>
                                </div>


                                <div class="form-group">
                                    <label for="status_id" class="control-label">Project Status</label>
                                    <select type="text" class="form-control select2" id="status_id" name="status_id">
                                        <option value="">Select Status</option>

                                        @foreach($statuses as $status)
                                            <option value="{{$status->id}}" >{{$status->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="status_id-error" class="control-label error"></label>
                                </div>

                                <div class="form-group">
                                    <label for="note" class="control-label">Note</label>
                                    <textarea class="form-control" id="note" name="note"></textarea>
                                    <label id="note-error" class="control-label error"></label>
                                </div>


                                <div class="form-group">
                                    <label for="attachment" class="control-label">Attachment</label>
                                    <div class="box image-box" >
                                        <a href="" class="popup_selector" data-inputid="company_image">Browse Attachment</a>
                                        <input type="text" id="attachment" name="attachment" value="">
                                    </div>
                                    <label id="attachment-error" class="control-label error"></label>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
                    @include('layouts.partials.form-action-buttons',['submit'=>true,'back'=>true])
            </form>
@endsection

@push('css')
    <link href="{{asset('css/colorbox.css')}}" rel="stylesheet">
@endpush
@push('js')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.min.js"></script>
    <script src="{{asset('packages/ckeditor/ckeditor.js')}}"></script>
    <script>
        CKEDITOR.replace( 'note' );
    </script>
    <script type="text/javascript" src="{{asset('js/jquery.colorbox-min.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/standalonepopup.min.js')}}"></script>

    <script>
        $(function(){

            $("input").on("change", function() {
                this.setAttribute(
                    "data-date",
                    moment(this.value, "YYYY-MM-DD")
                        .format( this.getAttribute("data-date-format") )
                )
            }).trigger("change");


        });
    </script>
    <script>
        $(function () {
            $('.select2').select2({
                width: '100%'
            });
        })
        $('#form-back').click(function () {
            location.href='{{route('lead-action.index')}}'+ '/' + {{app('request')->get('lead_id')}} + '/edit'
        });
        $('#form-reset').on('click',function () {
            $('#main-form')[0].reset();
        })
        $('#form-submit').click(function () {
            var counter = 0;
            @foreach($fields['store'] as $k=>$field)

            if( $('#{{$field}}').val() =='' ){
                $('#{{$field}}-error').text('This field is required');
                counter++;
            }
            @endforeach
            if ( counter > 0 ){
                return;
            }
            // tinyMCE.triggerSave();
            var data = new FormData();
            var content = CKEDITOR.instances.note.getData();

            //Form data
            var form_data = $('#main-form').serializeArray();
            $.each(form_data, function (key, input) {
                data.append(input.name, input.value);
            });
            data.append('_token', '{{csrf_token()}}');
            data.append('note', content);

            $.ajax({
                type: "POST",
                processData: false,
                contentType: false,
                url: '{{route('lead-action.store')}}',
                data: data,
                success: function(data)
                {
                    console.log(data);
                    if(data != null){
                        location.href='{{route('project-management.lead-system.lead.index')}}'+ '/' + data.leadAction.lead_id + '/edit#leadAction';
                    }
                },
                error:function( data){
                    console.log(data);
                }
            });

        });
    </script>
@endpush