routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

function getUrlParent($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null){
        return $pm->slug.'/';
    }
    else {
       return   getUrlParent($pm->parent_id). $pm->slug.'/';
    }

}


function getUrlController($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null) {
        return $pm->controller_name.'\\';
    }
    else {
        return   getUrlController($pm->parent_id). $pm->controller_name.'\\';
    }

}

function getUrlName($parent_id ){
    if ( $parent_id == null )
        return'';
    $pm = \App\Models\ParentModule::find($parent_id);
    if ( $pm->parent_id == null) {
        return $pm->slug.'.';
    }
    else {
        return   getUrlName($pm->parent_id). $pm->slug.'.';
    }

}

Route::get('/', function () {
    return redirect('/cms');
})->name('welcome');

Auth::routes();
Route::get('cms/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('cms/login', 'Auth\LoginController@login')->name('login');

Route::post('/contact-us/mail','HomeController@mailContact')->name('contact.post');
Route::get('/ajax-select', 'HomeController@ajaxSelect')->name('ajax-select');

Route::group([ 'middleware' => ['roles'], 'prefix'=>'cms'], function () {
    $modules = \App\Models\Module::all();
    foreach ( $modules as $module ){

        Route::resource( getUrlParent($module->parent_id).$module->slug, getUrlController($module->parent_id).$module->controller_name,
            ['as' => substr(getUrlName($module->parent_id), 0, -1)]);
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{id}/remove-image',
            getUrlController($module->parent_id).$module->controller_name.'@removeImage')
            ->name(getUrlName($module->parent_id).$module->slug.'.removeImage');

        Route::get(getUrlParent($module->parent_id).$module->slug.'/{id}/edit/authorize',
            getUrlController($module->parent_id).$module->controller_name.'@editAuthorise')
            ->name(getUrlName($module->parent_id).$module->slug.'.edit-authorise');
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{user}/up', getUrlController($module->parent_id).$module->controller_name.'@up')
            ->name(getUrlName($module->parent_id).$module->slug.'.up');
        Route::get(getUrlParent($module->parent_id).$module->slug.'/{user}/down', getUrlController($module->parent_id).$module->controller_name.'@down')
            ->name(getUrlName($module->parent_id).$module->slug.'.down');
    }
    Route::get('/', 'HomeController@index')->name('home');
    $pmodules = \App\Models\ParentModule::query()->whereNull('parent_id')->get();
    foreach ($pmodules as $mod){

//        \Illuminate\Support\Facades\Log::info($mod->hasConfig());
        Route::get($mod->slug, $mod->controller_name.'\\'.$mod->controller_name.'Controller@show')->name($mod->slug);
        if ( $mod->hasConfig()->count() > 0){
            Route::get($mod->slug.'/configuration', $mod->controller_name.'\\'.$mod->controller_name.'Controller@configuration')
                ->name($mod->slug.'.configuration');
            Route::post($mod->slug.'/configuration', $mod->controller_name.'\\'.$mod->controller_name.'Controller@configuration')
                ->name($mod->slug.'.configuration.store');
        }
    }

    Route::group([ 'prefix'=>'configuration','middleware' => ['roles'] ], function () {
        Route::get('remove/{key}','Configuration\ConfigurationController@removeImage')->name('configuration.remove');
        Route::get('branding','Configuration\ConfigurationController@indexBranding')->name('configuration.branding');
        Route::post('branding','Configuration\ConfigurationController@brandingStore')->name('configuration.branding.store');
        Route::get('domain','Configuration\ConfigurationController@indexDomain')->name('configuration.domain');
        Route::post('domain','Configuration\ConfigurationController@domainStore')->name('configuration.domain.store');
        Route::get('super-user','Configuration\ConfigurationController@indexSuperUser')->name('configuration.super-user');
        Route::post('super-user','Configuration\ConfigurationController@superUserStore')->name('configuration.super-user.store');
        
        Route::resource('api-argument', 'Configuration\ApiArgumentController');
        Route::get('api-argument/{api-argument}/up', 'Configuration\ApiArgumentController@up')->name('api-argument.up');
        Route::get('api-argument/{api-argument}/down', 'Configuration\ApiArgumentController@down')->name('api-argument.down');Route::get('api-argument/{id}/edit/authorize','Configuration\ApiArgumentController@editAuthorise')->name('api-argument.edit-authorise');


        Route::resource('contact-phone', 'OrganizationsManagement\ContactSystem\ContactPhoneController');
        Route::get('contact-phone/{contact-phone}/up', 'OrganizationsManagement\ContactSystem\ContactPhoneController@up')->name('contact-phone.up');
        Route::get('contact-phone/{contact-phone}/down', 'OrganizationsManagement\ContactSystem\ContactPhoneController@down')->name('contact-phone.down');Route::get('lead-action/{id}/edit/authorize','ProjectManagement\ProjectSystem\LeadActionController@editAuthorise')->name('lead-action.edit-authorise');



        Route::resource('api-generator','Configuration\ApiController');
        Route::get('api-generator/{api}/up', 'Configuration\ApiController@up')->name('api-generator.up');
        Route::get('api-generator/{api}/down', 'Configuration\ApiController@down')->name('api-generator.down');
        Route::get('api-generator/{id}/edit/authorize','Configuration\ApiController@editAuthorise')->name('api-generator.edit-authorise');

        Route::resource('domain', 'Configuration\DomainController');
        Route::get('domain/{domain}/up', 'Configuration\DomainController@up')->name('domain.up');
        Route::get('domain/{domain}/down', 'Configuration\DomainController@down')->name('domain.down');
        Route::get('domain/{id}/edit/authorize','Configuration\DomainController@editAuthorise')->name('domain.edit-authorise');

        Route::resource('status', 'Configuration\StatusController');
        Route::get('status/{status}/up', 'Configuration\StatusController@up')->name('status.up');
        Route::get('status/{status}/down', 'Configuration\StatusController@down')->name('status.down');
        Route::get('status/{id}/edit/authorize','Configuration\StatusController@editAuthorise')->name('status.edit-authorise');



        Route::get('language','Configuration\ConfigurationController@indexLanguage')->name('configuration.language');
        Route::get('language/change/{language}','Configuration\ConfigurationController@languageChange')->name('configuration.language.change');
        Route::get('language/create','Configuration\ConfigurationController@createLang')->name('configuration.language.create');
        Route::post('language/store','Configuration\ConfigurationController@storeLanguage')->name('configuration.language.store');


    });
    Route::group(['middleware' => ['roles'] ], function () {

        Route::resource('project-management/dashboard', 'ProjectManagement\ProjectSystem\DashboardController');
        Route::get('project-management/dashboard', 'ProjectManagement\ProjectSystem\DashboardController@index')->name('project-management/dashboard.index');

        Route::get('user','ProfileController@edit')->name('profile');
        Route::get('user/remove-image','ProfileController@removeImage')->name('profile.removeImage');
        Route::post('user/update','ProfileController@update')->name('profile.update');

        Route::resource('lead-action', 'ProjectManagement\LeadSystem\LeadActionController');
        Route::get('lead-action/{lead-action}/up', 'ProjectManagement\LeadSystem\LeadActionController@up')->name('lead-action.up');
        Route::get('lead-action/{lead-action}/down', 'ProjectManagement\LeadSystem\LeadActionController@down')->name('lead-action.down');
        Route::get('lead-action/{id}/edit/authorize','ProjectManagement\LeadSystem\LeadActionController@editAuthorise')->name('lead-action.edit-authorise');

        Route::resource('project-module', 'ProjectManagement\ProjectSystem\ProjectModuleController');
        Route::get('project-module/{project-module}/up', 'ProjectManagement\ProjectSystem\ProjectModuleController@up')->name('project-module.up');
        Route::get('project-module/{project-module}/down', 'ProjectManagement\ProjectSystem\ProjectModuleController@down')->name('project-module.down');
        Route::get('project-module/{id}/edit/authorize','ProjectManagement\ProjectSystem\ProjectModuleController@editAuthorise')->name('project-module.edit-authorise');

        Route::resource('project-task', 'ProjectManagement\ProjectSystem\ProjectTaskController');
        Route::get('project-task/{project-task}/up', 'ProjectManagement\ProjectSystem\ProjectTaskController@up')->name('project-task.up');
        Route::get('project-task/{project-task}/down', 'ProjectManagement\ProjectSystem\ProjectTaskController@down')->name('project-task.down');
        Route::get('project-task/{id}/edit/authorize','ProjectManagement\ProjectSystem\ProjectTaskController@editAuthorise')->name('project-task.edit-authorise');

    });

});

app/Http/Controllers/Configuration/ApiArgumentController.php
<?php

namespace App\Http\Controllers\Configuration;

use App\Models\ApiArgument;
use App\Models\Api;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class ApiArgumentController extends  Controller
{
    //



    public function index(Request $request){


        if ( $request->ajax() ){
            if($request->has('api_id')){
                return DataTables::of($this->listModel(new ApiArgument(), [['api_id',$request->get('api_id')]]))->make(true);
            }
            return DataTables::of($this->listModel(new ApiArgument()))->make(true);
        }

        $model = new ApiArgument();
        $fields = $model->fields();
        $add_button ='Add Api Argument';
        $filters = [
            'type' => ['Api', 'Sub']
        ];

        return view('configuration.api-argument.api-argument',compact('fields','add_button','filters'));
    }


    public function show($apiArgument){

        $apiArgument = $this->findApiArgumentById($apiArgument);
        $title = 'ApiArgument '.$apiArgument->name;

        return view('configuration.api-argument.api-argument-show', compact('title','apiArgument'));
    }

    public function create(){
        $model = new ApiArgument();
        $fields = $model->fields();
        return view('configuration.api-argument.api-argument',['title'=>'New Api Argument','fields'=>$fields]);
    }

    public function store(Request $request){
        $params = $request->except('_token');

        $apiArgument =  $this->createApiArgument($params);
        return ['status'=> 'success','apiArgument'=>$apiArgument];
    }

    public function edit($apiArgument){
        $apiArgument = $this->findApiArgumentById($apiArgument);
        $model = new ApiArgument();
        $fields = $model->fields();
        $title = 'Update '.$apiArgument->name;

        return view('configuration.api-argument.api-argument-update',['title'=>$title, 'fields'=>$fields, 'apiArgument'=>$apiArgument]);
    }
    
    public function editAuthorise($id){
        return response()->json(['status'=>'success']);
    }

    public function update(Request $request, $apiArgument){
        $params = $request->except('_token');
        $params['slug'] = str_slug($request->input('name'));

        $this->updateApiArgument($params, $apiArgument);
        $apiArgument = $this->findApiArgumentById($apiArgument);

        return ['status'=> 'success','apiArgument'=>$apiArgument];
    }

    public function destroy ( $apiArgument){
        if( $this->deleteApiArgument($apiArgument) ){
            return "success";
        }else{
            return 'failed';
        }
    }

    public function up($apiArgument){
        return ApiArgument::find($apiArgument)->moveOrderUp();

    }
    public function down($apiArgument){
        return ApiArgument::find($apiArgument)->moveOrderDown();
    }


    private function findApiArgumentById(int $id) :ApiArgument
    {
        return ApiArgument::query()->where('id',$id)->get()->first();
    }


    private function createApiArgument(array $params)
    {
        try {

            $apiArgument = new ApiArgument($params);
            $apiArgument->save();
            return $apiArgument;
        } catch (\Exception $e) {
            return null;
        }
    }

    private function updateApiArgument(array $params, int $id)
    {
        try {
            return ApiArgument::query()->find($id)->update($params);
        } catch (\Exception $e) {
            return false;
        }
    }

    private function deleteApiArgument(int $id)
    {

       try {
            return ApiArgument::query()->find($id)->delete();
       } catch (\Exception $e) {
           return false;
       }
    }

}

app/Http/Controllers/Configuration/DomainController.php
<?php

namespace App\Http\Controllers\Configuration;

use App\Models\Domain;
use App\Utils\TextField;
use App\Utils\Transform;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\Facades\DataTables;

class DomainController extends  Controller
{
    //

    use Transform;


    public function index(Request $request){


        if ( $request->ajax() ){
            return DataTables::of($this->listDomains())->make(true);
        }

        $model = new Domain();
        $fields = $model->fields();
        $add_button ='Add Domain';
        $filters = [
            'type' => ['Domain', 'Sub']
        ];

        return view('configuration.domains.domains',compact('fields','add_button','filters'));
    }


    public function show($domain){

        $domain = $this->findDomainById($domain);
        $title = 'Domain '.$domain->name;

        return view('configuration.domains.domain-show', compact('title','domain'));
    }

    public function create(){

        $model = new Domain();
        $fields = $model->fields();
        return view('configuration.domains.domain',['title'=>'New Domain','fields'=>$fields]);
    }

    public function editAuthorise($id){
        return response()->json(['status'=>'success']);
    }
    
    public function store(Request $request){
        $params = $request->except('_token');

        $domain =  $this->createDomain($params);
        return $domain;
    }

    public function edit($domain){
        $domain = $this->findDomainById($domain);

        $model = new Domain();
        $fields = $model->fields();

        $title = 'Update '.$domain->name;

        return view('configuration.domains.domain-update',['title'=>$title, 'fields'=>$fields, 'domain'=>$domain]);
    }


    public function update(Request $request, $domain){
        $params = $request->except('_token');
        $params['slug'] = str_slug($request->input('name'));

        $this->updateDomain($params, $domain);
        $domain = $this->findDomainById($domain);

        return $domain;
    }

    public function destroy ( $domain){
        if( $this->deleteDomain($domain) ){
            return "success";
        }else{
            return 'failed';
        }
    }

    public function up($domain){
        return Domain::find($domain)->moveOrderUp();

    }
    public function down($domain){
        return Domain::find($domain)->moveOrderDown();
    }


    private function findDomainById(int $id) :Domain
    {
        return Domain::query()->where('id',$id)->get()->first();
    }

    private function listDomains($id = null)
    {
        if ( $id  == null ){
            $modulesPage =  Domain::query()
                ->where('parent_id', null)
                ->orderBy('order','desc')
                ->get();
            $modules = $modulesPage->map( function (Domain $module){
                return $this->transformIndexDomain($module);
            })->all();
        }else{
            $modulesPage =  Domain::query()
                ->where('parent_id', null)
                ->orderBy('order','desc')
                ->get();
            $modules = $modulesPage->map( function (Domain $module){
                return $this->transformIndexDomain($module);
            })->all();
        }

        return $modules;
    }

    private function createDomain(array $params)
    {
        try {

            $domain = new Domain($params);
            $domain->save();
            return $domain;
        } catch (\Exception $e) {
            return null;
        }
    }

    private function updateDomain(array $params, int $id)
    {
        try {
            return Domain::query()->find($id)->update($params);
        } catch (\Exception $e) {
            return false;
        }
    }

    private function deleteDomain(int $id)
    {

//        try {
            return Domain::query()->find($id)->delete();
//        } catch (\Exception $e) {
//            return false;
//        }
    }

}

resources/views/configuration/status/status-update.blade.php
@extends('layouts.app')
@php($model = new \App\Models\Api())
@php($fields = $model->fields())
@section('content')
            <form id="main-form">
                <input type="text" name="_method" value="put" hidden>
                @csrf
                <div id="1" class="tab-content tab-content-profile" style="display:block;">
                    <div class="row">
                        <div class="container">
                            <div class="col-md-11">
                                <div class="form-group">
                                    <label for="name" class="control-label">Name<span class="star-required">*</span></label>
                                    <input type="text" class="form-control" id="name" name="name"  value="{{$status->name}}">
                                    <label id="name-error" class="control-label error"></label>
                                </div>
                                <div class="form-group">
                                    <label for="module_id" class="control-label">Module</label>
                                    <select type="text" class="form-control select2" id="module_id" name="module_id" >
                                        <option value="" >Select Module</option>
                                        @foreach($modules as $module)
                                            <option value="{{$module->id}}" @if($module->id == $status->module_id)selected @endif >{{$module->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="module_id-error" class="control-label error"></label>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                @include('layouts.partials.form-action-buttons',['submit'=>true,'reset'=>true])
            </form>

@endsection

@push('css')

    <link href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <link href="{{asset('css/colorbox.css')}}" rel="stylesheet">
@endpush
@push('js')


    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>

    <script type="text/javascript" src="{{asset('js/jquery.colorbox-min.js')}}"></script>


    <script>
        $(function () {
            $('.select2').select2({
                width:'100%'
            });


            $('#form-back').click(function () {
                location.href='{{route('status.index')}}'
            });
            $('#form-reset').on('click',function () {
                $('#main-form')[0].reset();
                $(".select2").val(null);
                $(".select2").trigger('change');
            })
            $('#form-submit').on('click',function () {
                var count = 0;
                @foreach($fields['update'] as $field)
                if($('#{{$field}}').val() == ''){
                    $('#{{$field}}-error').html('This field is required');
                    count++;
                }else{
                    $('#{{$field}}-error').html('');
                }
                @endforeach

                if(count == 0){
                    $.ajax({
                        type: "POST",
                        url: '{{route('status.update', $status->id)}}',
                        data: $('#main-form').serialize(),
                        dataType: 'json',
                        success: function(data)
                        {
                            if(data.status == 'success'){
                                location.href='{{route('status.index')}}';
                            } else{
                                for( var error in  data.messages){
                                    $('#'+error+'-error').html(data.messages[error]);
                                }
                            }
                            console.log(data);
                            // if ( data != null )
                            //
                        },
                        error:function( data){
                            console.log(data);
                        }
                    });
                }
            });
        })
    </script>

@endpush

resources/views/configuration/status/status.blade.php
@extends('layouts.app')
@php($model = new \App\Models\Api())
@php($fields = $model->fields())
@section('content')

            <form id="main-form">
                @csrf
                <div id="1" class="tab-content tab-content-profile" style="display:block;">
                    <div class="row">
                        <div class="container">
                            <div class="col-md-11">
                                <div class="form-group">
                                    <label for="name" class="control-label">Name<span class="star-required">*</span></label>
                                    <input type="text" class="form-control" id="name" name="name"  >
                                    <label id="name-error" class="control-label error"></label>
                                </div>
                                <div class="form-group">
                                    <label for="module_id" class="control-label">Module</label>
                                    <select type="text" class="form-control select2" id="module_id" name="module_id" >
                                        <option value="" >Select Module</option>
                                    @foreach($modules as $module)
                                            <option value="{{$module->id}}"  >{{$module->name}}</option>
                                        @endforeach
                                    </select>
                                    <label id="module_id-error" class="control-label error"></label>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
                @include('layouts.partials.form-action-buttons',['submit'=>true,'reset'=>true])
            </form>

@endsection

@push('css')

    <link href="http://cdn.rawgit.com/Eonasdan/bootstrap-datetimepicker/a549aa8780dbda16f6cff545aeabc3d71073911e/build/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <link href="{{asset('css/colorbox.css')}}" rel="stylesheet">
@endpush
@push('js')


    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.9.0/moment-with-locales.js"></script>

    <script type="text/javascript" src="{{asset('js/jquery.colorbox-min.js')}}"></script>

    <script>
        $(function () {
            $('.select2').select2({
                width:'100%'
            });


            $('#form-back').click(function () {
                location.href='{{route('status.index')}}'
            });
            $('#form-reset').on('click',function () {
                $('#main-form')[0].reset();
                $(".select2").val(null);
                $(".select2").trigger('change');
            })
            $('#form-submit').on('click',function () {
                var count = 0;
                @foreach($fields['store'] as $field)
                if($('#{{$field}}').val() == ''){
                    $('#{{$field}}-error').html('This field is required');
                    count++;
                }else{
                    $('#{{$field}}-error').html('');
                }
                @endforeach

                if(count == 0){
                    $.ajax({
                        type: "POST",
                        url: '{{route('status.store')}}',
                        data: $('#main-form').serialize(),
                        dataType: 'json',
                        success: function(data)
                        {
                            if(data.status == 'success'){
                                location.href='{{route('status.index')}}';
                            } else{
                                for( var error in  data.messages){
                                    $('#'+error+'-error').html(data.messages[error]);
                                }
                            }
                            console.log(data);
                            // if ( data != null )
                            //
                        },
                        error:function( data){
                            console.log(data);
                        }
                    });
                }
            });
        })
    </script>

@endpush

resources/views/configuration/status/statuses.blade.php
@extends('layouts.app')

@section('content')
            @include('layouts.partials.ajax-tables', ['route'=>Request::url(),'active'=>'status', 'type' => 'status'])

@endsection